services:
  api:
    container_name: "authorization-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: authorization-db
      DB_HOST: postgres_db
      DB_PORT: 5432
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
    depends_on:
        - db

  db:
    container_name: postgres_db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authorization-db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: