auth0:
  audience: ${AUTH0_AUDIENCE:https://snipet-searcher.com}
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}
  token-url: https://dev-dxya2auaytwzj1s4.us.auth0.com/oauth/token
spring:
  application:
    name: resource-service-with-auth-example
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI:https://dev-dxya2auaytwzj1s4.us.auth0.com/}
